services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
      - '4943:4943'
    env_file: .env
    environment:
      - NODE_ENV=development
      - QUIKDB_USERNAME
      - QUIKDB_EMAIL
      - QUIKDB_PASSWORD
      - QUIKDB_PRINCIPAL_ID
      - QUIKDB_PROJECT_TOKEN_REF
      - DFX_NETWORK=local
      - RUST_BACKTRACE=1
      - DFX_BIND_ADDRESS=0.0.0.0:4943
    volumes:
      - .:/usr/src/app
      - quikdb_config:/root/.quikdb
      - dfx_config:/root/.config/dfx
      - dfx-data:/root/.dfx
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    healthcheck:
      test:
        [
          'CMD',
          'bash',
          '-c',
          'curl -f http://127.0.0.1:4943/_/raw || curl -f http://0.0.0.0:4943/_/raw'
        ]
      interval: 10s # Reduced interval
      timeout: 5s # Reduced timeout
      retries: 5 # Increased retries
      start_period: 30s # Increased start period
    security_opt:
      - no-new-privileges:true
    networks:
      - quikdb_network

networks:
  quikdb_network:
    driver: bridge
volumes:
  quikdb_config:
    driver: local
  dfx_config:
    driver: local
  dfx-data:
    driver: local
