services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '3000:3000'
      - '4943:4943'
    env_file: .env
    environment:
      - NODE_ENV=development
      - QUIKDB_USERNAME
      - QUIKDB_EMAIL
      - QUIKDB_PASSWORD
      - QUIKDB_PRINCIPAL_ID
      - QUIKDB_PROJECT_TOKEN_REF
      - DFX_NETWORK=local
      - RUST_BACKTRACE=1
      - DFX_DEBUG=1
      - DFX_BIND_ADDRESS=0.0.0.0:4943
    volumes:
      - .:/usr/src/app
      - quikdb_config:/root/.quikdb
      - dfx_config:/root/.config/dfx
      - dfx-data:/root/.dfx
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -sf http://localhost:4943/_/raw || curl -sf http://0.0.0.0:4943/_/raw || exit 1'
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    command: sh -c "./init-quikdb.sh"
    restart: unless-stopped
    network_mode: 'host'

volumes:
  quikdb_config:
    driver: local
  dfx_config:
    driver: local
  dfx-data:
    driver: local
